development:
  adapter: postgresql
  encoding: unicode
  database: stratMap_development
  pool: 5
  username: <%= ENV["PG_Username"] %>
  password: <%= ENV["PG_Password"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: stratMap_test
  pool: 5
  username: <%= ENV["PG_Username"] %>
  password: <%= ENV["PG_Password"] %>
